// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.inspur.grpc.proto;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc_proto.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseParam = 1;</code>
   */
  java.lang.String getResponseParam();
  /**
   * <code>string responseParam = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseParamBytes();
}
