// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.inspur.grpc.proto;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc_proto.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestParam = 1;</code>
   */
  java.lang.String getRequestParam();
  /**
   * <code>string requestParam = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestParamBytes();
}
