// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.inspur.grpc.proto;

public interface StudentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc_proto.StudentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();

  /**
   * <code>string city = 3;</code>
   */
  java.lang.String getCity();
  /**
   * <code>string city = 3;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();
}
